"""changed language_code and product description

Revision ID: 01d9baea1559
Revises: 804682fdc9c4
Create Date: 2022-07-14 10:58:05.340635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d9baea1559'
down_revision = '804682fdc9c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'language_code', type_=sa.VARCHAR(10), nullable=False)
    op.alter_column('products', 'description', type_=sa.VARCHAR(3000), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'description', type_=sa.TEXT, nullable=True)
    op.alter_column('users', 'language_code', type_=sa.VARCHAR(255), nullable=False)
    # ### end Alembic commands ###
